---
dependency:
  name: galaxy
driver:
  name: vagrant
  default_box: "${VAGRANT_DEFAULT_BOX}"
platforms:
  - name: instance
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
provisioner:
  name: ansible
verifier:
  name: ansible
